# To use your Dockerfile to build a custom runtime, set the runtime field to [runtime: custom]
runtime: custom 
env: flex

runtime_config:
    python_version: <3>

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 50
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1